version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - checkout

      - run:
          name: site
          command: mvn site
      - run:
          name: post-site
          command: mvn post-site
      - run:
          name: test
          command: mvn test
      - run:
          name: javadoc
          command: mvn javadoc:javadoc
      - add_ssh_keys:
          fingerprints:
            - "e0:87:fe:a4:c6:73:3c:b2:f6:7c:6c:ac:1e:f9:3d:c9"

      - run:
          name: upload_javadoc
          command: |
            git config --global user.name "Mounier-JeanChristophe"
            git config --global user.email "jean-christophe.mounier@alumni.univ-avignon.fr"
            git clone --branch=gh-pages --depth=1 git@github.com:Mounier-JeanChristophe/ceri-m1-techniques-de-test.git gh-pages
            rm -rf gh-pages/*
            cp -R target/site/apidocs/* gh-pages/
            cd gh-pages
            git add .
            git commit -m "javadoc uploaded successfully"
            git push origin gh-pages
            
      - store_artifacts:
          path: target/site/jacoco/jacoco.xml
      - store_artifacts:
          path: target/checkstyle-result.xml
      - store_artifacts:
          path: target/site/checkstyle-result.svg
      - codecov/upload


workflows:
  maven_test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      


