version: 2.1

orbs:
  maven: circleci/maven@1.4.0

jobs:
  test:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test

workflows:
  maven_test:
    jobs:
      - test:
        filters:
          branches:
            only:
              - master


