version: 2.1

orbs:
  maven: circleci/maven@1.4.0

workflows:
  maven_test:
    jobs:
      - maven/test

executors:
  my-custom-executor:
    docker:
      - image: cimg/openjdk:15.0

jobs:
  filters:
    branches:
      only:
        - master

    executor: my-custom-executor
    steps:
      - checkout
      - run:
          name: Build
          command: mvn -B -DskipTests clean package
      - run:
          name: Test
          command: mvn test

