version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  codecov: codecov/codecov@3.2.4

jobs:
  test:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path:  target
  codecov:
    docker:
      - image: cimg/base:stable
    steps:
      - codecov/upload
      - run: 
           name: codecov-1
           command: curl -Os https://uploader.codecov.io/latest/linux/codecov
      - run: 
          name: codecov-2
          command: chmod +x codecov
      - run: 
          name: codecov-3
          command: ./codecov 

workflows:
  maven_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      - codecov:
          filters:
            branches:
              only:
                - master


