version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  codecov: codecov/codecov@3.2.4

jobs:
  build-and-test:
    docker:
      - image: cimg/openjdk:15.0
    steps:
      - checkout

      - run:
          name: site
          command: mvn site
      - run:
          name: post-site
          command: mvn post-site
      - run:
          name: test
          command: mvn test
      - store_artifacts:
          path: target/site/jacoco/jacoco.xml
      - store_artifacts:
          path: target/checkstyle-result.xml
      - store_artifacts:
          path: target/site/checkstyle-result.svg
      - codecov/upload


workflows:
  maven_test:
    jobs:
      - build-and-test:
          filters:
            branches:
              only:
                - master
      


