version: 2.1

orbs:
  maven: circleci/maven@1.4.0
  codecov: codecov/codecov@3.2.4

jobs:
  test:
    docker:
      - image: cimg/openjdk:15.0
      - image: checkstyle/idea-docker:jdk11-idea2022.2.2 
    steps:
      - checkout
      - run:
          name: Test
          command: mvn test
      - store_artifacts:
          path:  target 
      - codecov/upload

      - run:
          name: Inspection
          command: |
            mkdir .idea
            cp config/intellij-idea-inspections-misc.xml .idea/misc.xml
            ./.ci/idea-inspection.sh
          no_output_timeout: 25m
          working_directory: ~/TP1
      - store_artifacts:
          path: /target


workflows:
  maven_test:
    jobs:
      - test:
          filters:
            branches:
              only:
                - master
      


