version: '2.1'

orbs:
  maven: circleci/maven@x.y

workflows:
  maven_test:
    jobs:
      - maven/test

executors:
  my-custom-executor:
    docker:
      - image: cimg/base:stable

jobs:
  test:

    executor: my-custom-executor
    steps:
      - checkout
      - run: |
          mvn test


